SIZE_PAGE = 24
ELASTICSEARCH_INDEX = 'car_elastic'
RANGE_PRICE_RELATED = 10000000
NUMBER_SAME_PRICE_PRODUCT_RELATED = 24
NUMBER_SAME_MANUFACTURER_PRODUCT_RELATED = 24
NUMBER_DATA_MATCHING = 6
NUMBER_PRODUCT_SAME_SOURCE = 6
